### ISSUE TITLE
line 8: syntax error: unexpected newline

### ISSUE THREAD

**Issue by sren00-d** [Admonstrator/glinet-remove-chinalock#1]
Thank you for the work. When I tired to run your script, it gives a syntax error. ( By the way, I am running it on MT6000 firmware version: 4.6.2). 

<img width="506" alt="Screenshot 2024-08-10 at 8 39 19 PM" src="https://github.com/user-attachments/assets/ee2fd3f9-9e31-4ecf-89cd-87d4ca7d2cdf">

**Comment by Admonstrator** [comment]
Please check if the download of the file was successful or copy it manually.
Line 8 does not contain script content - so the issue should be that the file is corrupt.

**Comment by sren00-d** [comment]
> Please check if the download of the file was successful or copy it manually. Line 8 does not contain script content - so the issue should be that the file is corrupt.

After copying the content, it worked. Thank you!
